# -*- coding: utf-8 -*-
"""Text_Summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgpY6vHRz0rEZPLO906VvUsyVOr0RXr5
"""

!pip install transformers

from transformers import pipeline

summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

article = input("Enter your Paragraph to Summarize: ")

summary = summarizer(article, min_length = 60, max_length = 120, do_sample = False)

print("Summary : ") , summary[0].get('summary_text')

!pip install rouge-score

from rouge_score import rouge_scorer

reference = """Creativity is the process of making new connections between existing ideas.
James Webb Young described five steps for creativity: gather material, work over ideas,
step away from the problem, allow insight to return, and develop ideas with feedback.
While creativity can be challenging, it can be cultivated into a habit to produce meaningful work."""

generated = """This page pulls together my most essential information about creativity. I’ll share how creativity works, how to find your hidden creative genius, and how to create meaningful work. The creative process is the act of making new connections between old ideas or recognizing relationships between concepts. While being creative isn’t easy, nearly all great ideas follow a similar creative process."""

scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)

# Calculate scores
scores = scorer.score(reference, generated)

for metric in ['rouge1', 'rouge2', 'rougeL']:
    score = scores[metric]
    print(f"{metric.upper()}: Precision={score.precision:.4f}, Recall={score.recall:.4f}, F1={score.fmeasure:.4f}")